### ISSUE TITLE
Undefined control sequence for \frontmatter, \mainmatter, and \backmatter

### ISSUE THREAD

**Issue by treforevans** [jessexknight/ut-thesis#1]
I tried to compile the following simple document
```
\documentclass{ut-thesis}
\author{Jane Doe}
\title{Title of the Example Thesis}
\degree{Doctor of Philosophy}
\department{Institute of Medical Science}
\gradyear{2020}
% \addbibresource{refs}
\usepackage{lipsum}
\begin{document}
\frontmatter
\maketitle
\begin{abstract}
\lipsum
\end{abstract}
\tableofcontents
\listoftables
\listoffigures
\mainmatter
\lipsum
\appendix
\backmatter
\lipsum
\end{document}
```
And got the following errors
```
! Undefined control sequence.
l.10 \frontmatter
...
! Undefined control sequence.
l.18 \mainmatter
...
! Undefined control sequence.
l.21 \backmatter
```
I've attached the full log file [here](https://github.com/jessexknight/ut-thesis/files/6057624/main.log).

It appears I'm using `v3.0.0a`

**Comment by jessexknight** [comment]
Thanks for the report. Line 7-8 from the log file says:
```
(C:\Users\trefor\AppData\Roaming\MiKTeX\2.9\tex/latex/ut-thesis\ut-thesis.cls
Document Class: ut-thesis 2012/06/01 v2.0 graduate theses at the University of 
```
So I think you're still using the old version. Maybe you can update the `ut-thesis` package via MiKTeX? Alternatively, I believe .cls files in the working directory will take precedence.

The new version is not fully backward compatible because we now inherit from the `book` class, rather than the `report` class.
Hope this help!

**Comment by treforevans** [comment]
I was indeed using the old version, it's working now with the new version.
Thanks you for the fast response!
