### ISSUE TITLE
Conflict of \degree Command

### ISSUE THREAD

**Issue by MrFrankfurter** [jessexknight/ut-thesis#14]
The \degree command is also used in the gensymb package as a degree symbol (for example for temperature units or angles), causing a conflict with the degree name from this class. This can be solved with a workaround to assign the degree symbol to a different command name, but it is messy and does not work 100%.

Since the gensymb package is likely used often with technical theses, it would be good to rename the \degree command to something which does not conflict, such as \degreetitle or \degreename.

**Comment by jessexknight** [comment]
Thanks for this. I'm surprised it never came up sooner.

I was tempted to rename `\degree` as you suggest, but also wary of breaking compatibility, especially because there are a surprising number of different versions of **ut-thesis** already floating around, and I don't want to add any stress to students during submission. Also, there is a cleaner workaround:

After using `\degree` (which internally assigns `\@degree` to hold the value) write: `\let\degree\undefined` (as described [here](https://tex.stackexchange.com/questions/35962)) or similarly `\let\degree\relax` ([here](https://tex.stackexchange.com/questions/20655)), which "frees" `\degree` to be redefined by any packages loaded later. See those links for more info / small caveats.

I also considered making the default behaviour of `\degree` (and perhaps other commands too) to undefine itself as described above, perhaps after `\maketitle` (in fact, this is the [default behaviour](https://tex.stackexchange.com/questions/452971) of article.cls). But this solution has always struck me as slightly overkill or unexpected.

Hope this helps you and/or future readers, but I don't think I'll make any changes to the class right now.

**Comment by jessexknight** [comment]
If helpful, here is a MWE:
```latex
\documentclass{ut-thesis}
\degree{Doctor of Philosophy}
\let\degree\relax % fix
\usepackage{gensymb}
\begin{document}
\maketitle % still works
\degree % also works
\end{document}
```

**Comment by MrFrankfurter** [comment]
Sounds good. Thanks, that is a cleaner workaround.

With everything in the preamble this way it still works well with the subfiles package too (vs. clearing the variable in the \maketitle command where it wouldn't be applied to the sub-documents, or clearing in the command itself where it would still conflict if the gensymb package was loaded before the \degree command in the preamble).

Also NB for anyone reading this that \degree should be the fully spelled out degree title to meet the SGS requirements.
