### ISSUE TITLE
In-text citations not appearing chronologically

### ISSUE THREAD

**Issue by marcoistasy** [jessexknight/ut-thesis#15]
Hello,

I am using the `ut-thesis.cls` file in my Overleaf project and the int-text citations are appearing out of order (please see the attached image). For instance, the in-text citations start at the number _10_ and _1_ does not appear until the next paragraph.  Is there any insight into what might be causing this problem?

<img width="614" alt="Screen Shot 2022-07-26 at 19 16 50" src="https://user-images.githubusercontent.com/7032741/181128419-42c57ab1-3ed9-4094-a02b-31db273f50f8.png">

**Comment by marcoistasy** [comment]
Adding for posterity, it was an issue with the bibliography style. The default biblipgraphy style is set to `alphabetic`, I beleive, but can be easily changed to, say, `ieee`,  by calling:

```
 \usepackage[backend=biber, style=ieee]{biblatex} % for references
```

**Comment by jessexknight** [comment]
Thanks --- although there is some example code in `test/`, there is nothing related to references or bibliography within **ut-thesis** itself, and so the class should be compatible with whatever bib tools you prefer. [Here](https://tex.stackexchange.com/questions/25701) is a helpful overview of those tools.

Another solution to your specific issue (since the `ieee` option may change other stuff beyond the order) can be found [here](https://tex.stackexchange.com/questions/51434).
