### ISSUE TITLE
Instructions for working with this template in Overleaf

### ISSUE THREAD

**Issue by JohnGiorgi** [jessexknight/ut-thesis#16]
Are there general instructions somewhere for getting this template working in Overleaf? I am sure I am just doing something silly, but it doesn't seem like like the `ut-thesis.cls` file for some reason.

**Comment by jessexknight** [comment]
There are some general installation tips [here](https://github.com/jessexknight/ut-thesis#installation). Hard to help without more specific error information.

In general **ut-thesis** is already available on Overleaf, since it is part of [texlive-publishers](https://packages.ubuntu.com/bionic/all/texlive-publishers/filelist), and [Overleaf uses TeX Live](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live) --- so you shouldn't have to upload `ut-thesis.cls`, unless you specifically want the bleeding edge version (which has had [only very minor changes](https://github.com/jessexknight/ut-thesis/blame/master/ut-thesis/ut-thesis.cls) since 2022). You should just be able to write `\documentclass{ut-thesis}`, unless there are errors unrelated to **ut-thesis**

**Comment by JohnGiorgi** [comment]
Sorry, to be more specific, I am just looking for general setup instructions, e.g." download this from here", "upload it to overleaf like this", "set this as the main file", etc etc. I feel this could be useful for students, given the popularity of overleaf. Could perhaps be added to README in this repo, on the ww.ctan.org archive or both

**Comment by jessexknight** [comment]
Please see the above documentation & README changes. Perhaps the main thing to note is the "complete" example code [here](https://github.com/jessexknight/ut-thesis/tree/master/test/full) on GitHub.

You shouldn't need to download / upload anything to Overleaf because ut-thesis is already available on Overleaf. Within the [main document](https://www.overleaf.com/learn/how-to/Set_Main_Document) on Overleaf, just use `\documentclass{ut-thesis}` like you would for an *article*, etc.

**Comment by JohnGiorgi** [comment]
I see, so starting a blank document with a `main.tex` file that looks something like this

```latex
\documentclass{ut-thesis}
\usepackage{graphicx} % Required for inserting images

\title{thesis}
\author{John Giorgi}
\date{February 2023}

\begin{document}

\maketitle

\section{Introduction}

\end{document}
```

would be the correct way to use the template overleaf?

**Comment by jessexknight** [comment]
Something like that. e.g. `\date` will go unused (instead use `\gradyear`) and you will eventually need to specify `\degree` and `\department` to override the placeholder values. Also, the top-level structural command will be `\chapter`, not `\section` as in _article_.

But the above boilerplate from Overleaf will indeed compile.

Again, [this example](https://github.com/jessexknight/ut-thesis/blob/master/test/full/main.tex) is a great starting place.

**Comment by JohnGiorgi** [comment]
Awesome, thanks @jessexknight, I will follow that example!
