### ISSUE TITLE
Page Numbering Style - Bottom of Page

### ISSUE THREAD

**Issue by alicarlos** [jessexknight/ut-thesis#17]
The page numbering appears on the top left/right of the page in the main chapters. 

But in the word template provided by SGS it is consistently at the bottom of the page. 
Also on according to the [SGS Template Website](https://www.sgs.utoronto.ca/current-students/program-completion/formatting/), the page numbering is suggested to be placed at the bottom center.

**Comment by jessexknight** [comment]
Thanks, I missed that specification. You're the first to mention of it though, so I assume that this has not been causing any rejected submissions. Upper right page numbers are more common in general, and are easier for flipping through & finding a page.

Unless SGS complains to me, I may leave the page numbers as-is on **ut-thesis** for now, since the chapter / section titles in the header are complemented by page numbers across the top corners, plus the better usability.

To match SGS' requirements exactly, you can replace the page header/footer code starting [here](https://github.com/jessexknight/ut-thesis/blob/master/ut-thesis/ut-thesis.cls#L171) with the following (then place the modified ut-thesis.cls file in your project directory to take priority over the distributed version):

```latex
\if@twoside
\renewcommand*{\ps@headings}%
  {\let\@mkboth\markboth
   \def\@oddfoot{\headerstyle{\hfill\thepage\hfill}}
   \let\@evenfoot\@oddfoot
   \def\@oddhead{\headerstyle{\rightmark\hfil}}%
   \def\@evenhead{\headerstyle{\hfil\leftmark}}%
   \def\chaptermark##1{\markboth{%
     \if@mainmatter\headerstyle{\@chapapp\ \thechapter.\ ##1}\fi}{}}
   \def\sectionmark##1{\markright{%
     \if@mainmatter\headerstyle{\thesection.\ ##1}\fi}}}
\else
\renewcommand*{\ps@headings}%
  {\let\@mkboth\markboth
   \def\@oddfoot{\headerstyle{\hfill\thepage\hfill}}
   \let\@evenfoot\@oddfoot
   \def\@oddhead{\headerstyle{\rightmark\hfil}}%
   \def\chaptermark##1{\markright{%
     \if@mainmatter\headerstyle{\@chapapp\ \thechapter.\ ##1}\fi}}}
\fi
```

**Comment by jessexknight** [comment]
@alicarlos just checking: did you have your thesis rejected by SGS / ProQuest for this issue? Thanks.
