### ISSUE TITLE
include list of tables and figures in the TOC

### ISSUE THREAD

**Issue by SaraMati** [jessexknight/ut-thesis#20]
The SGS requires this now: 
Please include the List of Tables, List of Figures, and the Table of Contents itself in the TOC as per the following example:

Example: 
Table of Contents     ……………………...  iv
List of Tables   ……………………………. vi
List of Figures   ....................................... vii
Introduction   ..........................................  1

**Comment by SaraMati** [comment]
solution: 
\usepackage[numbib]{tocbibind}

**Comment by jessexknight** [comment]
Hi Sara, did SGS email this to you? If so, could you kindly fwd this to my email? I will reply and try to stop this foolishness. I have never seen the TOF, TOT, or TOC itself in the TOC of a published work.

It's worth noting that SGS and ProQuest both consider each other to be the ultimate authority on formatting, so that arbitrary guidelines whimmed by administrators are mistakenly interpreted as hard rules.

For completeness, some other solutions to the original problem [here](https://tex.stackexchange.com/q/106093).

**Comment by SaraMati** [comment]
I know, bizarre. but we won't get the graduation confirmation letter if the thesis doesn't get accepted by ETD admin, so I did what they asked. I need that letter ASAP. forwarded you their email.

**Comment by jessexknight** [comment]
Thanks, got it! & I replied trying to make the case ...

Nobody at SGS or ProQuest can describe the rationale or origins of the requirements, and I suspect they are arbitrary.
